WITH
    formatDateTime(addMonths(now(), -40), '%Y-01') AS p_month_star, formatDateTime(now(), '%Y-%m') AS p_month_dt, toYYYYMM(toDate(concat(toYear(addMonths(now(), -40)), '-01-01'))) AS p_monthstar, toYYYYMM(now()) AS p_monthdt
SELECT '销售'                                                                                   AS data_type,
       '1'                                                                                      AS data_flag,
       t.month_dt                                                                               AS month_dt,
       t.d_corp_id                                                                              AS d_corp_id,
       t.d_corp_code,
       t.d_corp_name,
       t.d_corp_sname,
       t.d_profit_region_name                                                                   AS d_profit_region_name,
       t.d_profit_corp_id                                                                       AS d_profit_corp_id,
       t.d_profit_corp_code,
       t.d_profit_corp_sname,
       t.d_material_id,
       t.d_material_code,
       t.d_material_name,
       multiIf(t.d_class_code2 = '23', '动保', t.d_class_code2 IN ('21', '22'), '饲料', '其他') AS product_tag,
       t.d_class_code4,
       t.d_class_name4,
       t.d_class_code6,
       t.d_class_name6,
       t.client_class_flag,
       t.d_client_id,
       t.d_client_code,
       t.d_client_name,
       t.d_salesman_id,
       t.d_salesman_code,
       t.d_salesman_name,
       t.d_bill_code                                                                            AS d_bill_code,
       t.is_gift,
       t.f_sale_amount,
       t.f_total_amount,
       t.f_num                                                                                  AS f_num,
       t.f_sale_num                                                                             AS f_sale_num,
       t.f_gift_num                                                                             AS f_gift_num,
       t.f_second_num                                                                           AS f_sale_second_num,
       t.f_discount_amount,
       toDecimal128(c.f_base_discount, 3) * toDecimal128(t.f_num, 3)                            AS f_base_discount,
       c.f_base_discount                                                                        AS f_base_discount_ton,
       toDecimal128(c.f_promotion_discount, 3) * toDecimal128(t.f_num, 3)                       AS f_promotion_discount,
       c.f_promotion_discount                                                                   AS f_promotion_discount_ton,
       b.f_cost_num,
       b.f_cost_amount,
       multiIf(t.is_gift = 'N', b.f_cost_amount, 0)                                             AS f_cost_amount1,
       multiIf(t.is_gift = 'Y', b.f_cost_amount, 0)                                             AS f_gift_cost_amount,
       b.f_cost_ton,
       'sal'                                                                                    AS d_billtype_code,
       '销售成本'                                                                               AS d_billtype_name,
       toDecimal128(0, 6)                                                                       AS f_rebate_amt,
       toDecimal128(0, 6)                                                                       AS f_rebate_qty,
       toDecimal128(0, 6)                                                                       AS f_payout_amt
FROM alphafeed.dwd_so_saleorder AS t
         LEFT JOIN alphafeed.dwd_so_priceform AS c
                   ON (c.dr = '0') AND (t.discount_id = c.priceform_uid) AND (toYYYYMM(c.ts) >= p_monthstar) AND
                      (toYYYYMM(c.ts) <= p_monthdt)
         LEFT JOIN
     (
         SELECT month_dt,
                d_bill_code,
                d_corp_id,
                order_row,
                sum(f_num)         AS f_cost_num,
                sum(f_cost_amount) AS f_cost_amount,
                sum(f_cost_ton)    AS f_cost_ton
         FROM alphafeed.dwd_so_cost
         WHERE (month_dt >= p_month_star)
           AND (month_dt <= p_month_dt)
           AND (dr = '0')
         GROUP BY month_dt,
                  d_bill_code,
                  d_corp_id,
                  order_row
         ) AS b ON (t.month_dt = b.month_dt) AND (t.d_bill_code = b.d_bill_code) AND (t.order_row = b.order_row) AND
                   (t.d_corp_id = b.d_corp_id)
WHERE (t.month_dt >= p_month_star)
  AND (t.month_dt <= p_month_dt)
  AND (t.dr = '0')
UNION ALL
WITH
    formatDateTime(addMonths(now(), -40), '%Y-01') AS p_month_star, formatDateTime(now(), '%Y-%m') AS p_month_dt, toYYYYMM(toDate(concat(toYear(addMonths(now(), -40)), '-01-01'))) AS p_monthstar, toYYYYMM(now()) AS p_monthdt
SELECT '返利'                                                                                         AS data_type,
       '2'                                                                                            AS data_flag,
       t.biz_mth                                                                                      AS month_dt,
       t.d_corp_id,
       t.d_corp_code,
       t.d_corp_name,
       t.d_corp_sname,
       t.d_profit_region_name                                                                         AS d_profit_region_name,
       t.d_profit_corp_id                                                                             AS d_profit_corp_id,
       t.d_profit_corp_code,
       t.d_profit_corp_sname,
       t.d_material_id,
       t.d_material_code,
       t.d_material_name,
       multiIf(dictGet('alphafeed.dim_material_dict', 'd_class_code2', t.d_material_id) = '23', '动保',
               dictGet('alphafeed.dim_material_dict', 'd_class_code2', t.d_material_id) IN ('21', '22'), '饲料',
               '其他')                                                                                AS product_tag,
       dictGet('alphafeed.dim_material_dict', 'd_class_code4', t.d_material_id)                       AS d_class_code4,
       dictGet('alphafeed.dim_material_dict', 'd_class_name4', t.d_material_id)                       AS d_class_name4,
       dictGet('alphafeed.dim_material_dict', 'd_class_code6', t.d_material_id)                       AS d_class_code6,
       dictGet('alphafeed.dim_material_dict', 'd_class_name6', t.d_material_id)                       AS d_class_name6,
       toString(dictGet('alphafeed.dim_client_dict', 'custclass_flag', (t.d_client_id,
                                                                        t.d_corp_id)))                AS client_class_flag,
       t.d_client_id,
       t.d_client_code,
       t.d_client_name,
       dictGet('alphafeed.dim_client_dict', 'd_salesman_id', (t.d_client_id, t.d_corp_id))            AS d_salesman_id,
       ''                                                                                             AS d_salesman_code,
       dictGet('alphafeed.dim_client_dict', 'd_salesman_name', (t.d_client_id,
                                                                t.d_corp_id))                         AS d_salesman_name,
       prm_billcode                                                                                   AS d_bill_code,
       'N'                                                                                            AS is_gift,
       toDecimal128(0, 6)                                                                             AS f_sale_amount,
       toDecimal128(0, 6)                                                                             AS f_total_amount,
       toDecimal128(0, 6)                                                                             AS f_num,
       toDecimal128(0, 6)                                                                             AS f_sale_num,
       toDecimal128(0, 6)                                                                             AS f_gift_num,
       toDecimal128(0, 6)                                                                             AS f_sale_second_num,
       toDecimal128(0, 6)                                                                             AS f_discount_amount,
       toDecimal128(0, 6)                                                                             AS f_base_discount,
       toDecimal128(0, 6)                                                                             AS f_base_discount_ton,
       toDecimal128(0, 6)                                                                             AS f_promotion_discount,
       toDecimal128(0, 6)                                                                             AS f_promotion_discount_ton,
       toDecimal128(0, 6)                                                                             AS f_cost_num,
       toDecimal128(0, 6)                                                                             AS f_cost_amount,
       toDecimal128(0, 6)                                                                             AS f_cost_amount1,
       toDecimal128(0, 6)                                                                             AS f_gift_cost_amount,
       toDecimal128(0, 6)                                                                             AS f_cost_ton,
       t.d_billtype_code,
       t.d_billtype_name,
       t.f_rebate_amt,
       t.f_rebate_qty,
       t.f_payout_amt
FROM alphafeed.dwd_cust_rebate_actual_m AS t
WHERE (t.biz_mth >= p_month_star)
  AND (t.biz_mth <= p_month_dt)
UNION ALL
WITH
    formatDateTime(addMonths(now(), -40), '%Y-01') AS p_month_star, formatDateTime(now(), '%Y-%m') AS p_month_dt, toYYYYMM(toDate(concat(toYear(addMonths(now(), -40)), '-01-01'))) AS p_monthstar, toYYYYMM(now()) AS p_monthdt
SELECT '返利红冲'                                                                                     AS data_type,
       '2'                                                                                            AS data_flag,
       t.close_mth                                                                                    AS month_dt,
       t.d_corp_id,
       t.d_corp_code,
       t.d_corp_name,
       t.d_corp_sname,
       t.d_profit_region_name                                                                         AS d_profit_region_name,
       t.d_profit_corp_id                                                                             AS d_profit_corp_id,
       t.d_profit_corp_code,
       t.d_profit_corp_sname,
       t.d_material_id,
       t.d_material_code,
       t.d_material_name,
       multiIf(dictGet('alphafeed.dim_material_dict', 'd_class_code2', t.d_material_id) = '23', '动保',
               dictGet('alphafeed.dim_material_dict', 'd_class_code2', t.d_material_id) IN ('21', '22'), '饲料',
               '其他')                                                                                AS product_tag,
       dictGet('alphafeed.dim_material_dict', 'd_class_code4', t.d_material_id)                       AS d_class_code4,
       dictGet('alphafeed.dim_material_dict', 'd_class_name4', t.d_material_id)                       AS d_class_name4,
       dictGet('alphafeed.dim_material_dict', 'd_class_code6', t.d_material_id)                       AS d_class_code6,
       dictGet('alphafeed.dim_material_dict', 'd_class_name6', t.d_material_id)                       AS d_class_name6,
       toString(dictGet('alphafeed.dim_client_dict', 'custclass_flag', (t.d_client_id,
                                                                        t.d_corp_id)))                AS client_class_flag,
       t.d_client_id,
       t.d_client_code,
       t.d_client_name,
       dictGet('alphafeed.dim_client_dict', 'd_salesman_id', (t.d_client_id, t.d_corp_id))            AS d_salesman_id,
       ''                                                                                             AS d_salesman_code,
       dictGet('alphafeed.dim_client_dict', 'd_salesman_name', (t.d_client_id,
                                                                t.d_corp_id))                         AS d_salesman_name,
       prm_billcode                                                                                   AS d_bill_code,
       'N'                                                                                            AS is_gift,
       toDecimal128(0, 6)                                                                             AS f_sale_amount,
       toDecimal128(0, 6)                                                                             AS f_total_amount,
       toDecimal128(0, 6)                                                                             AS f_num,
       toDecimal128(0, 6)                                                                             AS f_sale_num,
       toDecimal128(0, 6)                                                                             AS f_gift_num,
       toDecimal128(0, 6)                                                                             AS f_sale_second_num,
       toDecimal128(0, 6)                                                                             AS f_discount_amount,
       toDecimal128(0, 6)                                                                             AS f_base_discount,
       toDecimal128(0, 6)                                                                             AS f_base_discount_ton,
       toDecimal128(0, 6)                                                                             AS f_promotion_discount,
       toDecimal128(0, 6)                                                                             AS f_promotion_discount_ton,
       toDecimal128(0, 6)                                                                             AS f_cost_num,
       toDecimal128(0, 6)                                                                             AS f_cost_amount,
       toDecimal128(0, 6)                                                                             AS f_cost_amount1,
       toDecimal128(0, 6)                                                                             AS f_gift_cost_amount,
       toDecimal128(0, 6)                                                                             AS f_cost_ton,
       t.d_billtype_code,
       t.d_billtype_name,
       t.f_payout_amt - t.f_rebate_amt                                                                AS f_rebate_amt,
       toDecimal128(0, 6)                                                                             AS f_rebate_qty,
       toDecimal128(0, 6)                                                                             AS f_payout_amt
FROM alphafeed.dwd_cust_rebate_actual_m AS t
WHERE (t.biz_mth >= p_month_star)
  AND (t.biz_mth <= p_month_dt)
  AND (is_reversal = 'Y')